import subprocess, os, re
from playwright.sync_api import sync_playwright, expect
os.makedirs("/tmp/bktest/shots2", exist_ok=True)
def sql(q): return subprocess.run(["su","postgres","-c",f"psql -h /tmp/pgtest -p 55432 -U postgres -Atq -c \"{q}\""],capture_output=True,text=True).stdout.strip()
sql("delete from bk_users; delete from bk_books;")
URL="http://127.0.0.1:8080/"
res=[]; problems=[]
def check(n, fn):
    try: fn(); res.append(True); print("PASS", n)
    except Exception as e: res.append(False); print("FAIL", n, "->", str(e).splitlines()[0][:220])
with sync_playwright() as p:
    br=p.chromium.launch(args=["--no-proxy-server"])
    c=br.new_context(viewport={"width":412,"height":915}, device_scale_factor=2, is_mobile=True, has_touch=True, locale="ko-KR")
    pg=c.new_page()
    pg.on("console", lambda m: m.type=="error" and problems.append(m.text))
    pg.on("pageerror", lambda e: problems.append("pageerror: "+str(e)))
    pg.goto(URL+"#/signup")
    pg.get_by_label("아이디").fill("owner_1"); pg.get_by_label("이름").fill("태관")
    pg.get_by_label("비밀번호", exact=True).fill("reading2026"); pg.get_by_label("비밀번호 한 번 더").fill("reading2026")
    pg.get_by_role("button", name="가입 신청 보내기").click()
    expect(pg.get_by_role("heading", name="승인을 기다리고 있어요")).to_be_visible()
    sql("update bk_users set status='approved', is_admin=true")
    pg.get_by_role("button", name="지금 확인하기").click()
    check("빈 서재 화면", lambda: expect(pg.get_by_text("읽고 있는 책이 없어요")).to_be_visible())
    pg.screenshot(path="/tmp/bktest/shots2/01-empty-shelf.png", full_page=True)
    pg.get_by_role("link", name="＋ 책 등록하기").click()
    check("책 등록 화면", lambda: expect(pg.get_by_role("heading", name="책 등록하기")).to_be_visible())
    pg.get_by_role("button", name="찾기", exact=True).click()
    check("빈 검색어 안내", lambda: expect(pg.get_by_role("alert")).to_contain_text("찾을 책"))
    pg.get_by_label("제목이나 저자로 찾기").fill("심리")
    pg.get_by_role("button", name="찾기", exact=True).click()
    check("검색 결과 2권", lambda: expect(pg.locator("#results .book-row")).to_have_count(2))
    check("표지 없는 책은 글자 표지", lambda: expect(pg.locator("#results .cover-blank").first).to_be_visible())
    pg.wait_for_timeout(600)
    pg.screenshot(path="/tmp/bktest/shots2/02-search.png", full_page=True)
    pg.locator("#results .book-row", has_text="사피엔스").click()
    check("확인 화면", lambda: expect(pg.get_by_role("heading", name="사피엔스")).to_be_visible())
    check("태그 없는 책 소개", lambda: expect(pg.get_by_text("인류의 역사를 다룬 책")).to_be_visible())
    pg.get_by_label("전체 쪽수 (선택)").fill("636")
    pg.screenshot(path="/tmp/bktest/shots2/03-confirm.png", full_page=True)
    pg.get_by_role("button", name="서재에 넣기").click()
    check("넣은 뒤 책 자세히 화면", lambda: expect(pg.get_by_role("heading", name="사피엔스")).to_be_visible() or expect(pg.get_by_role("button", name="서재에서 빼기")).to_be_visible())
    check("상태 '읽는 중' 선택됨", lambda: expect(pg.locator("#status-form input[value=reading]")).to_be_checked())
    pg.get_by_label("읽은 쪽").fill("700"); pg.get_by_role("button", name="쪽수 저장").click()
    check("전체보다 많은 쪽 막음", lambda: expect(pg.locator("#pages .form-error")).to_contain_text("많아요"))
    pg.get_by_label("읽은 쪽").fill("159"); pg.get_by_role("button", name="쪽수 저장").click()
    check("쪽수 저장 → 25%", lambda: expect(pg.get_by_text("159 / 636쪽 · 25%")).to_be_visible())
    check("진행 막대 길이 적용", lambda: pg.wait_for_function("document.querySelector('.bar') && document.querySelector('.bar').style.width==='25%'", timeout=3000))
    pg.screenshot(path="/tmp/bktest/shots2/04-detail.png", full_page=True)
    pg.locator("label.chip", has_text="다 읽음").click()
    check("다 읽음 → 636쪽 100%", lambda: expect(pg.get_by_text("636 / 636쪽 · 100%")).to_be_visible())
    check("다 읽은 날 자동 입력", lambda: expect(pg.get_by_label("다 읽은 날")).not_to_have_value(""))
    pg.get_by_role("button", name="← 서재").click()
    check("서재 '다 읽음 1'", lambda: expect(pg.get_by_role("button", name="다 읽음 1")).to_be_visible())
    pg.get_by_role("button", name="다 읽음 1").click()
    check("다 읽음 목록에 사피엔스", lambda: expect(pg.locator(".book-row", has_text="사피엔스")).to_be_visible())
    # 같은 책 다시 검색 → 내 서재에 있음
    pg.get_by_role("link", name="＋ 책 등록하기").click()
    check("검색 결과 유지 + '내 서재에 있음'", lambda: expect(pg.locator(".book-row", has_text="사피엔스").get_by_text("내 서재에 있음")).to_be_visible())
    # 바코드 화면 (시험 브라우저는 바코드 인식 없음 → 숫자 입력)
    pg.get_by_role("link", name="바코드 찍기").click()
    check("바코드 미지원 안내", lambda: expect(pg.locator("#scan-help")).to_contain_text("숫자를 적어"))
    pg.get_by_label("또는 바코드 아래 숫자 13자리로 찾기").fill("9788934972465"); pg.get_by_role("button", name="이 번호로 찾기").click()
    check("검산 틀린 번호 막음", lambda: expect(pg.get_by_role("alert")).to_contain_text("13자리"))
    pg.get_by_label("또는 바코드 아래 숫자 13자리로 찾기").fill("979-11-6850-334-2"); pg.get_by_role("button", name="이 번호로 찾기").click()
    check("번호로 찾아 확인 화면", lambda: expect(pg.get_by_role("heading", name="돈의 심리학")).to_be_visible())
    pg.screenshot(path="/tmp/bktest/shots2/05-scan-confirm.png", full_page=True)
    pg.locator("label.chip", has_text="읽고 싶은").click()
    pg.get_by_role("button", name="서재에 넣기").click()
    check("읽고 싶은 책으로 넣음", lambda: expect(pg.locator("#status-form input[value=want]")).to_be_checked())
    # 없는 번호 → 다시 찍기
    pg.goto(URL+"#/scan")
    pg.get_by_label("또는 바코드 아래 숫자 13자리로 찾기").fill("9788970123455"); pg.get_by_role("button", name="이 번호로 찾기").click()
    check("없는 책 안내 + 다시 찍기", lambda: (expect(pg.get_by_role("alert")).to_contain_text("직접 입력"), expect(pg.get_by_role("button", name="다시 찍기")).to_be_visible()))
    # 직접 입력
    pg.goto(URL+"#/add-manual")
    pg.get_by_role("button", name="서재에 넣기").click()
    check("제목 없으면 안내", lambda: expect(pg.get_by_role("alert")).to_contain_text("제목"))
    pg.get_by_label("제목").fill("<b>우리 동네</b> 문집"); pg.get_by_label("저자 (선택)").fill("홍길동, 김철수")
    pg.get_by_role("button", name="서재에 넣기").click()
    check("직접 입력 책 저장 · 글자 그대로 표시(태그 실행 안 됨)", lambda: expect(pg.get_by_role("heading", name="<b>우리 동네</b> 문집")).to_be_visible())
    check("글자 표지 표시", lambda: expect(pg.locator(".book-head .cover-blank")).to_be_visible())
    pg.get_by_role("button", name="서재에서 빼기").click()
    pg.get_by_role("dialog").get_by_role("button", name="빼기").click()
    check("빼고 서재로", lambda: expect(pg.get_by_role("heading", name="태관님의 서재")).to_be_visible())
    check("읽고 있는 책 0", lambda: expect(pg.get_by_text("읽고 있는 책이 없어요")).to_be_visible())
    pg.get_by_role("button", name="읽고 싶은 1").click()
    pg.wait_for_timeout(500)
    pg.screenshot(path="/tmp/bktest/shots2/06-shelf.png", full_page=True)
    check("남의 책 주소로 들어가면 안내", lambda: (pg.goto(URL+"#/book/00000000-0000-0000-0000-000000000000"), expect(pg.get_by_text("서재에서 이 책을 찾을 수 없어요.")).to_be_visible()))
    # 로그아웃 후 다른 사람 로그인 시 이전 목록 안 보임
    pg.goto(URL+"#/me"); pg.get_by_role("button", name="로그아웃").click()
    sql("insert into bk_users(username,password_hash,display_name,status) select 'other_1', password_hash, '다른이', 'approved' from bk_users where username='owner_1'")
    pg.get_by_label("아이디").fill("other_1"); pg.get_by_label("비밀번호", exact=True).fill("reading2026"); pg.get_by_role("button", name="로그인").click()
    check("다른 사람 로그인 시 앞사람 책 안 보임", lambda: (expect(pg.get_by_role("heading", name="다른이님의 서재")).to_be_visible(), expect(pg.get_by_text("읽고 있는 책이 없어요")).to_be_visible(), expect(pg.get_by_role("button", name="읽고 싶은 0")).to_be_visible()))
    br.close()
print(f"\n{sum(res)}/{len(res)} 통과")
real=[x for x in problems if "Failed to load resource" not in x]
print("브라우저 오류/CSP 위반:", len(real)); [print(" ", x[:250]) for x in real]
