# 4단계 화면 시험: 독서 시간 (타이머 · 서재 알림 · 멈춤/계속/끝내기 · 6시간 넘김 · 손으로 적기 · 고치기 · 지우기 · PC 이어 보기)
import subprocess, os
from playwright.sync_api import sync_playwright, expect
SHOTS = "/tmp/bktest/shots4"; os.makedirs(SHOTS, exist_ok=True)
URL = "http://127.0.0.1:8080/"
def sql(q): return subprocess.run(["su","postgres","-c",f"psql -h /tmp/pgtest -p 55432 -U postgres -Atq -c \"{q}\""],capture_output=True,text=True).stdout.strip()
res = []; problems = []
def check(n, fn):
    try:
        r = fn()
        if r is False: raise Exception("조건 불만족")
        res.append(True); print("PASS", n)
    except Exception as e: res.append(False); print("FAIL", n, "->", str(e).splitlines()[0][:240])
sql("delete from bk_users; delete from bk_books;")
QUIET = "window.__buzz = 0; navigator.vibrate = () => { window.__buzz++; return true; }; const _A = window.Audio; window.Audio = function(){ window.__buzz++; return new _A(); };"
def running_id(): return sql("select id from bk_reading_logs where ended_at is null and method='timer'")
def clock_secs(pg):
    h, m, s = [int(x) for x in pg.locator("#clock").inner_text().split(":")]; return h * 3600 + m * 60 + s

with sync_playwright() as p:
    br = p.chromium.launch(args=["--no-proxy-server"])
    c = br.new_context(viewport={"width": 412, "height": 915}, device_scale_factor=2, is_mobile=True, has_touch=True, locale="ko-KR")
    c.add_init_script(QUIET)
    pg = c.new_page()
    pg.on("console", lambda m: m.type == "error" and "fonts.g" not in m.text and "status of 4" not in m.text and problems.append(m.text))
    pg.on("pageerror", lambda e: problems.append("pageerror: " + str(e)))
    pg.goto(URL + "#/signup")
    pg.get_by_label("아이디").fill("owner_1"); pg.get_by_label("이름").fill("태관")
    pg.get_by_label("비밀번호", exact=True).fill("reading2026"); pg.get_by_label("비밀번호 한 번 더").fill("reading2026")
    pg.get_by_role("button", name="가입 신청 보내기").click()
    expect(pg.get_by_role("heading", name="승인을 기다리고 있어요")).to_be_visible()
    sql("update bk_users set status='approved', is_admin=true")
    pg.get_by_role("button", name="지금 확인하기").click()
    expect(pg.get_by_role("heading", name="태관님의 서재")).to_be_visible()
    for q, name, st in [("사피엔스", "사피엔스", "읽고 싶은"), ("심리", "돈의 심리학", "읽는 중")]:
        pg.goto(URL + "#/add"); pg.get_by_label("제목이나 저자로 찾기").fill(q); pg.get_by_role("button", name="찾기", exact=True).click()
        pg.locator("#results .book-row", has_text=name).click()
        pg.locator("label.chip", has_text=st).click()
        if name == "사피엔스": pg.get_by_label("전체 쪽수 (선택)").fill("636")
        pg.get_by_role("button", name="서재에 넣기").click()
        expect(pg.get_by_role("button", name="서재에서 빼기")).to_be_visible()
        if name == "사피엔스": book_url = pg.url
        else: money_url = pg.url
    pg.goto(book_url)
    check("책 화면 「독서 시간」: [독서 시작] · [시간 적기] · 빈 안내", lambda: (expect(pg.get_by_role("button", name="독서 시작")).to_be_enabled(), expect(pg.get_by_role("link", name="시간 적기")).to_be_visible(), expect(pg.get_by_text("아직 적은 독서 시간이 없어요")).to_be_visible()))

    # ── 타이머 시작 ──
    pg.get_by_role("button", name="독서 시작").click()
    check("[독서 시작] → 큰 시계 화면", lambda: (expect(pg.locator("#clock")).to_be_visible(), expect(pg.locator("#timer-state")).to_have_text("읽는 중"), expect(pg.get_by_role("button", name="멈춤")).to_be_visible()))
    check("앱을 닫아도 시간이 간다는 안내", lambda: expect(pg.get_by_text("앱을 닫거나 화면이 꺼져도")).to_be_visible())
    pg.wait_for_timeout(2300)
    check("시계가 1초씩 감", lambda: clock_secs(pg) >= 2)
    pg.screenshot(path=f"{SHOTS}/01-timer.png", full_page=True)
    check("읽고 싶은 책을 시작하면 「읽는 중」으로", lambda: sql("select status from bk_shelf s join bk_books b on b.id=s.book_id where b.title='사피엔스'") == "reading")
    pg.goto(URL + "#/shelf")
    check("서재 맨 위에 「읽는 중」 알림 + 시계", lambda: (expect(pg.locator(".running-banner")).to_contain_text("「사피엔스」 읽는 중"), expect(pg.locator("#banner-clock")).not_to_have_text("0:00:00")))
    pg.screenshot(path=f"{SHOTS}/02-shelf-banner.png")
    pg.reload()
    check("앱을 다시 열어도 알림 그대로(서버에 적힘)", lambda: expect(pg.locator(".running-banner")).to_be_visible())
    pg.goto(book_url)
    check("책 화면: 읽는 중 시계, [독서 시작] 숨김", lambda: (expect(pg.locator("#book-clock")).to_be_visible(), expect(pg.get_by_role("button", name="독서 시작")).to_be_hidden()))
    pg.goto(money_url)
    pg.get_by_role("button", name="독서 시작").click()
    check("다른 책은 시작 못 함 → 안내 창", lambda: (expect(pg.locator("dialog")).to_contain_text("「사피엔스」 타이머가 돌고 있어요"), expect(pg.locator("dialog").get_by_role("button", name="그 타이머 보기")).to_be_visible()))
    pg.locator("dialog").get_by_role("button", name="그 타이머 보기").click()
    check("[그 타이머 보기] → 타이머 화면", lambda: expect(pg.locator("#clock")).to_be_visible())

    # ── 멈춤 → 저장 (32분 · 120쪽) ──
    sql(f"update bk_reading_logs set started_at=now()-interval '32 minutes 10 seconds' where id='{running_id()}'")
    pg.reload(); expect(pg.locator("#clock")).to_be_visible()
    check("시계는 서버의 시작 시각 기준(0:32:xx)", lambda: 32 * 60 <= clock_secs(pg) < 33 * 60 + 5)
    pg.get_by_role("button", name="멈춤").click()
    check("멈춤 → 「32분 읽었어요」 · 쪽수 칸(지금 0쪽 / 전체 636쪽)", lambda: (expect(pg.locator("#stop-summary")).to_have_text("32분 읽었어요."), expect(pg.locator("#timer-state")).to_have_text("멈춤"), expect(pg.get_by_text("지금 0쪽 / 전체 636쪽")).to_be_visible()))
    s1 = clock_secs(pg); pg.wait_for_timeout(1500)
    check("멈추면 시계도 멈춤", lambda: clock_secs(pg) == s1)
    pg.screenshot(path=f"{SHOTS}/03-stop.png", full_page=True)
    pg.get_by_label("몇 쪽까지 읽었나요? (선택)").fill("700"); pg.get_by_role("button", name="저장").click()
    check("전체보다 많은 쪽 막음", lambda: expect(pg.get_by_role("alert")).to_contain_text("636"))
    pg.get_by_label("몇 쪽까지 읽었나요? (선택)").fill("120"); pg.get_by_role("button", name="저장").click()
    check("저장 → 책 화면 · 목록 「32분 · 120쪽까지 · 타이머」 · 합계", lambda: (expect(pg.locator(".log-row")).to_have_count(1), expect(pg.locator(".log-row")).to_contain_text("32분"), expect(pg.locator(".log-row")).to_contain_text("120쪽까지"), expect(pg.locator(".log-row")).to_contain_text("타이머"), expect(pg.locator("#log-total")).to_have_text("모두 32분")))
    check("책 진행도 120 / 636쪽", lambda: expect(pg.get_by_text("120 / 636쪽")).to_be_visible())
    check("[독서 시작] 다시 보임 · 알림 사라짐", lambda: (expect(pg.get_by_role("button", name="독서 시작")).to_be_visible(), pg.goto(URL + "#/shelf") or True, expect(pg.locator(".running-banner")).to_have_count(0)))

    # ── 계속 읽기 · 기록하지 않고 끝내기 ──
    pg.goto(book_url); pg.get_by_role("button", name="독서 시작").click(); expect(pg.locator("#clock")).to_be_visible()
    pg.get_by_role("button", name="멈춤").click()
    check("1분이 안 되면 저장 막고 안내", lambda: (expect(pg.locator("#stop-summary")).to_have_text("1분이 안 됐어요."), pg.get_by_role("button", name="저장").click() or True, expect(pg.get_by_role("alert")).to_contain_text("1분 이상")))
    pg.get_by_role("button", name="계속 읽기").click()
    s2 = clock_secs(pg); pg.wait_for_timeout(1600)
    check("[계속 읽기] → 시계 다시 감", lambda: (expect(pg.locator("#timer-state")).to_have_text("읽는 중"), clock_secs(pg) > s2))
    pg.get_by_role("button", name="멈춤").click(); pg.get_by_role("button", name="기록하지 않고 끝내기").click()
    pg.locator("dialog").get_by_role("button", name="끝내기").click()
    check("[기록하지 않고 끝내기] → 기록 안 남음", lambda: (expect(pg.get_by_role("button", name="서재에서 빼기")).to_be_visible(), sql("select count(*) from bk_reading_logs") == "1"))

    # ── 6시간 넘게 켜 둠 ──
    pg.get_by_role("button", name="독서 시작").click(); expect(pg.locator("#clock")).to_be_visible()
    sql(f"update bk_reading_logs set started_at=now()-interval '7 hours' where id='{running_id()}'")
    pg.reload(); expect(pg.locator("#clock")).to_be_visible()
    pg.get_by_role("button", name="멈춤").click()
    check("6시간 넘으면 실제 읽은 시간 고치기 안내 + 칸(420)", lambda: (expect(pg.locator("#long-note")).to_be_visible(), expect(pg.get_by_label("실제로 읽은 시간 (분)")).to_have_value("420")))
    pg.screenshot(path=f"{SHOTS}/04-long.png", full_page=True)
    pg.get_by_label("실제로 읽은 시간 (분)").fill("90"); pg.get_by_role("button", name="저장").click()
    check("고친 시간(1시간 30분)으로 저장", lambda: (expect(pg.locator(".log-row").first).to_contain_text("1시간 30분"), expect(pg.locator("#log-total")).to_have_text("모두 2시간 2분")))

    # ── 손으로 적기 · 고치기 · 지우기 ──
    pg.get_by_role("link", name="시간 적기").click()
    check("시간 적기: 오늘 날짜 기본 · 빨리 고르기", lambda: (expect(pg.get_by_role("heading", name="독서 시간 적기")).to_be_visible(), pg.get_by_label("읽은 날").input_value() == sql("select (now() at time zone 'Asia/Seoul')::date"), expect(pg.locator("[data-min]")).to_have_count(5)))
    pg.get_by_role("button", name="저장").click()
    check("분을 안 적으면 막음", lambda: expect(pg.get_by_role("alert")).to_contain_text("읽은 시간"))
    pg.locator("[data-min='30']").click()
    check("[30분] 누르면 칸에 30", lambda: expect(pg.get_by_label("읽은 시간 (분)")).to_have_value("30"))
    pg.get_by_label("읽은 날").fill("2026-09-01"); pg.get_by_label("몇 쪽까지 읽었나요? (선택)").fill("60")
    pg.screenshot(path=f"{SHOTS}/05-manual.png", full_page=True)
    pg.get_by_role("button", name="저장").click()
    check("저장 → 목록에 「9. 1. (화) · 30분 · 적음」", lambda: (expect(pg.locator(".log-row", has_text="적음")).to_contain_text("9. 1. (화)"), expect(pg.locator(".log-row", has_text="적음")).to_contain_text("30분")))
    check("앞쪽(60)을 적어도 읽은 쪽 120 그대로", lambda: expect(pg.get_by_text("120 / 636쪽")).to_be_visible())
    pg.screenshot(path=f"{SHOTS}/06-book-logs.png", full_page=True)
    pg.locator(".log-row", has_text="적음").click()
    check("기록 누르면 고치기 화면(값 채워짐)", lambda: (expect(pg.get_by_role("heading", name="독서 시간 고치기")).to_be_visible(), expect(pg.get_by_label("읽은 시간 (분)")).to_have_value("30"), expect(pg.get_by_label("읽은 날")).to_have_value("2026-09-01")))
    pg.get_by_label("읽은 시간 (분)").fill("45"); pg.get_by_role("button", name="고친 내용 저장").click()
    check("고친 내용 저장 → 45분", lambda: expect(pg.locator(".log-row", has_text="적음")).to_contain_text("45분"))
    pg.locator(".log-row", has_text="타이머").first.click()
    check("타이머 기록도 고칠 수 있음(시작 시각 안내)", lambda: expect(pg.get_by_text("타이머로 잰 기록이에요")).to_be_visible())
    pg.go_back()
    pg.locator(".log-row", has_text="적음").click()
    pg.get_by_role("button", name="이 기록 지우기").click(); pg.locator("dialog").get_by_role("button", name="지우기").click()
    check("지우기 → 목록에서 사라짐", lambda: (expect(pg.locator(".log-row")).to_have_count(2), expect(pg.locator("#log-total")).to_have_text("모두 2시간 2분")))
    check("소리 · 진동 없음", lambda: pg.evaluate("window.__buzz") == 0 and pg.locator("audio").count() == 0)

    # ── 폰에서 시작 → PC 에서 이어 보기 ──
    pg.get_by_role("button", name="독서 시작").click(); expect(pg.locator("#clock")).to_be_visible()
    sql(f"update bk_reading_logs set started_at=now()-interval '5 minutes' where id='{running_id()}'")
    c2 = br.new_context(viewport={"width": 1280, "height": 900}, locale="ko-KR")
    pg2 = c2.new_page()
    pg2.goto(URL + "#/login")
    pg2.get_by_label("아이디").fill("owner_1"); pg2.get_by_label("비밀번호", exact=True).fill("reading2026")
    pg2.get_by_role("button", name="로그인").click()
    check("PC 서재에도 「읽는 중」 알림", lambda: expect(pg2.locator(".running-banner")).to_contain_text("사피엔스"))
    pg2.locator(".running-banner").click()
    check("PC 타이머도 같은 시작 시각(0:05:xx)", lambda: (expect(pg2.locator("#clock")).to_be_visible(), 300 <= clock_secs(pg2) < 330))
    pg2.get_by_role("button", name="멈춤").click(); pg2.get_by_role("button", name="저장").click()
    check("PC 에서 멈춰 저장(5분)", lambda: expect(pg2.locator(".log-row").first).to_contain_text("5분"))
    pg2.screenshot(path=f"{SHOTS}/07-pc.png")
    pg.goto(URL + "#/shelf")
    check("폰 서재에서도 알림 사라짐", lambda: (pg.reload() or True, expect(pg.locator(".running-banner")).to_have_count(0)))
    check("자바스크립트 오류 없음", lambda: (_ for _ in ()).throw(Exception(problems)) if problems else True)
    br.close()
print(f"\n{sum(res)}/{len(res)} 통과")
