import subprocess, time, os, json
from playwright.sync_api import sync_playwright, expect
os.makedirs("/tmp/bktest/shots", exist_ok=True)
def sql(q): return subprocess.run(["su","postgres","-c",f"psql -h /tmp/pgtest -p 55432 -U postgres -Atq -c \"{q}\""],capture_output=True,text=True).stdout.strip()
sql("delete from bk_users")
URL="http://127.0.0.1:8080/"
results=[]; problems=[]
def check(name, fn):
    try: fn(); results.append((name,True)); print("PASS", name)
    except Exception as e: results.append((name,False)); print("FAIL", name, "->", str(e).splitlines()[0][:200])
def watch(page, who):
    page.on("console", lambda m: m.type in ("error","warning") and problems.append(f"[{who}] console {m.type}: {m.text}"))
    page.on("pageerror", lambda e: problems.append(f"[{who}] pageerror: {e}"))
with sync_playwright() as p:
    br = p.chromium.launch(args=["--no-proxy-server"])
    phone = dict(viewport={"width":412,"height":915}, device_scale_factor=2, is_mobile=True, has_touch=True, locale="ko-KR")
    owner = br.new_context(**phone); o = owner.new_page(); watch(o,"owner")
    o.goto(URL); 
    check("처음 열면 로그인 화면", lambda: expect(o.get_by_role("heading", name="book-log")).to_be_visible())
    o.screenshot(path="/tmp/bktest/shots/01-login.png")
    check("빈칸으로 로그인하면 안내", lambda: (o.get_by_role("button", name="로그인").click(), expect(o.get_by_role("alert")).to_have_text("아이디를 입력해 주세요.")))
    o.get_by_role("link", name="가입 신청하기").click()
    check("가입 화면으로 이동", lambda: expect(o.get_by_role("heading", name="가입 신청")).to_be_visible())
    o.get_by_label("아이디").fill("Owner_1")
    check("아이디 입력 시 소문자로 바뀜", lambda: expect(o.get_by_label("아이디")).to_have_value("owner_1"))
    o.get_by_label("이름").fill("태관")
    o.get_by_label("비밀번호", exact=True).fill("reading2026")
    o.get_by_label("비밀번호 한 번 더").fill("reading2027")
    o.get_by_role("button", name="가입 신청 보내기").click()
    check("비밀번호 두 개 다르면 안내", lambda: expect(o.get_by_role("alert")).to_have_text("두 비밀번호가 서로 달라요."))
    o.get_by_label("비밀번호 한 번 더").fill("reading2026")
    o.screenshot(path="/tmp/bktest/shots/02-signup.png")
    o.get_by_role("button", name="가입 신청 보내기").click()
    check("가입하면 승인 대기 화면", lambda: expect(o.get_by_role("heading", name="승인을 기다리고 있어요")).to_be_visible())
    o.screenshot(path="/tmp/bktest/shots/03-pending.png")
    check("새로 고쳐도 대기 화면 유지(출입증 저장)", lambda: (o.reload(), expect(o.get_by_role("heading", name="승인을 기다리고 있어요")).to_be_visible()))
    check("대기 중엔 서재 주소로 가도 막힘", lambda: (o.goto(URL+"#/shelf"), expect(o.get_by_role("heading", name="승인을 기다리고 있어요")).to_be_visible()))
    # 첫 관리자 만들기 (실제로는 승인받은 명령 한 줄)
    sql("update bk_users set status='approved', is_admin=true, approved_at=now() where username='owner_1'")
    o.get_by_role("button", name="지금 확인하기").click()
    check("승인되면 서재로 바뀜", lambda: expect(o.get_by_role("heading", name="태관님의 서재")).to_be_visible())
    o.screenshot(path="/tmp/bktest/shots/04-shelf.png", full_page=True)
    check("아래 탭 4개", lambda: expect(o.get_by_role("navigation", name="주요 화면").get_by_role("link")).to_have_count(4))
    o.get_by_role("link", name="통계").click()
    check("준비 중 탭 열림", lambda: expect(o.get_by_role("heading", name="통계")).to_be_visible())
    o.screenshot(path="/tmp/bktest/shots/05-soon.png")

    reader = br.new_context(**phone); r = reader.new_page(); watch(r,"reader")
    r.goto(URL+"#/signup")
    r.get_by_label("아이디").fill("reader2"); r.get_by_label("이름").fill("지민")
    r.get_by_label("비밀번호", exact=True).fill("bookworm99"); r.get_by_label("비밀번호 한 번 더").fill("bookworm99")
    r.get_by_role("button", name="가입 신청 보내기").click()
    check("두 번째 사람 대기", lambda: expect(r.get_by_role("heading", name="승인을 기다리고 있어요")).to_be_visible())

    o.goto(URL+"#/shelf"); o.reload()
    check("관리자 서재에 승인 대기 알림", lambda: expect(o.get_by_text("승인을 기다리는 회원이 1명 있어요.")).to_be_visible())
    o.screenshot(path="/tmp/bktest/shots/06-shelf-admin-notice.png")
    o.get_by_role("button", name="보기").click()
    check("회원 관리 화면", lambda: expect(o.get_by_role("heading", name="회원 관리")).to_be_visible())
    check("대기 목록에 지민", lambda: expect(o.locator(".person-name", has_text="지민")).to_be_visible())
    o.screenshot(path="/tmp/bktest/shots/07-admin.png", full_page=True)
    o.get_by_role("button", name="승인", exact=True).click()
    check("승인 후 대기 목록 비어짐", lambda: expect(o.get_by_text("승인을 기다리는 회원이 없어요.")).to_be_visible())
    r.get_by_role("button", name="지금 확인하기").click()
    check("지민 화면도 서재로", lambda: expect(r.get_by_role("heading", name="지민님의 서재")).to_be_visible())

    o.get_by_role("button", name="모든 회원").click()
    row = o.locator(".person", has_text="지민")
    row.get_by_role("button", name="임시 비밀번호").click()
    o.get_by_role("dialog").get_by_role("button", name="만들기").click()
    temp = {}
    def got_temp():
        expect(o.get_by_role("dialog").get_by_role("heading", name="임시 비밀번호")).to_be_visible()
        temp["v"] = o.locator("code.secret").inner_text().strip(); assert len(temp["v"])==10
    check("임시 비밀번호 창", got_temp)
    o.screenshot(path="/tmp/bktest/shots/08-temp-password.png")
    o.get_by_role("dialog").get_by_role("button", name="닫기").click()
    check("임시 비밀번호 발급하면 지민 기기는 로그아웃", lambda: (r.reload(), expect(r.get_by_role("heading", name="book-log")).to_be_visible()))
    r.get_by_label("아이디").fill("reader2"); r.get_by_label("비밀번호", exact=True).fill(temp.get("v",""))
    r.get_by_role("button", name="로그인").click()
    check("임시 비밀번호로 로그인", lambda: expect(r.get_by_role("heading", name="지민님의 서재")).to_be_visible())
    # 지민이 비밀번호 바꾸기
    r.get_by_role("button", name="나").click()
    r.get_by_label("지금 비밀번호").fill(temp.get("v","")); r.get_by_label("새 비밀번호", exact=True).fill("mybooks2026"); r.get_by_label("새 비밀번호 한 번 더").fill("mybooks2026")
    r.get_by_role("button", name="비밀번호 저장").click()
    check("비밀번호 바꾸기 알림", lambda: expect(r.locator("#toast")).to_contain_text("비밀번호를 바꿨어요"))
    r.screenshot(path="/tmp/bktest/shots/09-me.png", full_page=True)
    # 사용 중지
    o.locator(".person", has_text="지민").get_by_role("button", name="사용 중지").click()
    o.get_by_role("dialog").get_by_role("button", name="사용 중지").click()
    check("중지 후 상태 표시", lambda: expect(o.locator(".person", has_text="지민").locator(".state")).to_have_text("사용 중지"))
    r.get_by_role("button", name="← 서재").click()
    r.reload()
    check("중지되면 지민은 로그인 화면으로", lambda: expect(r.get_by_role("heading", name="book-log")).to_be_visible())
    r.get_by_label("아이디").fill("reader2"); r.get_by_label("비밀번호", exact=True).fill("mybooks2026"); r.get_by_role("button", name="로그인").click()
    check("중지된 계정 로그인 안내", lambda: expect(r.get_by_role("alert")).to_contain_text("사용이 중지된 계정"))
    r.screenshot(path="/tmp/bktest/shots/10-disabled-login.png")
    # 한도 저장
    o.get_by_label("한 사람이 하루에 [글자 읽기]를 누를 수 있는 횟수").fill("120"); o.get_by_role("button", name="저장").click()
    check("한도 저장", lambda: expect(o.locator("#toast")).to_contain_text("하루 120번"))
    sql("update bk_settings set value='100' where key='ocr_daily_limit'")
    # 로그아웃
    o.get_by_role("button", name="← 나").click(); o.get_by_role("button", name="로그아웃").click()
    check("로그아웃 → 로그인 화면", lambda: expect(o.get_by_role("heading", name="book-log")).to_be_visible())
    check("서비스 워커 등록", lambda: o.wait_for_function("navigator.serviceWorker && navigator.serviceWorker.getRegistration().then(r=>!!r)", timeout=5000))
    # PC 화면
    pc = br.new_context(viewport={"width":1280,"height":800}, locale="ko-KR"); q = pc.new_page(); watch(q,"pc")
    q.goto(URL); q.get_by_label("아이디").fill("owner_1"); q.get_by_label("비밀번호", exact=True).fill("reading2026"); q.get_by_role("button", name="로그인").click()
    check("PC에서도 로그인", lambda: expect(q.get_by_role("heading", name="태관님의 서재")).to_be_visible())
    q.screenshot(path="/tmp/bktest/shots/11-pc.png")
    br.close()
ok=sum(1 for _,v in results if v)
print(f"\n{ok}/{len(results)} 통과")
real=[x for x in problems if "fonts.g" not in x and "Failed to load resource: net::ERR" not in x]
print("브라우저 오류/CSP 위반:", len(real)); [print(" ", x[:250]) for x in real]
print("(글꼴 서버 접속 불가 경고:", len(problems)-len(real), "건 — 시험 컴퓨터가 구글 글꼴에 못 나가서 생김)")
